// Copyright 2024, code automatically generated by:A. Badilla, Joseph Valverde &
// Kenneth Villalobos
#include "Headers.hpp"
int main() {
  if (Number::spawn(3) + Number::spawn(2) > Number::spawn(4)) {
    ;
  } else {
    if (Number::spawn(3) + Number::spawn(2) > Number::spawn(6)) {
      ;
    } else {
    }
  };
  if ((String::spawn(hola) & Number::spawn(1)) and
      (Number::spawn(True) |) > Number::spawn(3)) {
    ;
  } else {
    if ((^^String::spawn(Kenneth)) == Number::spawn(0)) {
      ;
      ;
    } else {
      if (((Number::spawn(6.7) + Number::spawn(4.7)) & Number::spawn(97.3)) >
          Number::spawn(5)) {
        ;
        ;
        ;
      } else {
        if ((Number::spawn(84) & Number::spawn(3)) < Number::spawn(2)) {
          ;
          ;
          ;
          ;
        } else {
          if ((String::spawn(Caballito) >> Number::spawn(1)) ==
              String::spawn(Zebra)) {
            ;
            ;
            ;
            ;
            ;
          } else {
            String::spawn(Joseph)
          }
        }
      }
    }
  };
  return 0;
}