// Copyright 2024, code automatically generated by:A. Badilla, Joseph Valverde &
// Kenneth Villalobos
#include "Headers.hpp"
int main() {
  auto a = Number::spawn(5);
  a = Number::spawn(6);
  return 0;
}