// Copyright 2024, code automatically generated by: A. Badilla, Joseph Valverde
// & Kenneth Villalobos
#include "Headers.hpp"
int main() {
  if (Number::spawn(3) + Number::spawn(2) > Number::spawn(4)) {
    ;
  } else if (Number::spawn(3) + Number::spawn(2) > Number::spawn(6)) {
    ;
  } else {
    ;
  };
  if ((String::spawn("hola") == String::spawn("mundo")) &&
          (Bool::spawn(true) || Bool::spawn(false)) ||
      Bool::spawn(true)) {
    ;
  } else if ((None::spawn() && None::spawn() && String::spawn("Kenneth")) ==
             Bool::spawn(false)) {
    ;
    ;
  } else if (((Number::spawn(6.7) + Number::spawn(4.7)) - Number::spawn(97.3)) >
             Number::spawn(5)) {
    ;
    ;
    ;
  } else if ((Number::spawn(84) - Number::spawn(3)) < Number::spawn(2)) {
    ;
    ;
    ;
    ;
  } else if (String::spawn("Caballito") == String::spawn("Zebra")) {
    ;
    ;
    ;
    ;
    ;
  } else {
    ;
  };
  return 0;
}